export const EUR_GET_REQUEST = 'EUR/EUR_GET_REQUEST';
export const EUR_GET_SUCCESS = 'EUR/EUR_GET_SUCCESS';
export const EUR_GET_FAILURE = 'EUR/EUR_GET_FAILURE';

export const EUR_GET_PERIOD_REQUEST = 'EUR/EUR_GET_PERIOD_REQUEST';
export const EUR_GET_PERIOD_SUCCESS = 'EUR/EUR_GET_PERIOD_SUCCESS';
export const EUR_GET_PERIOD_FAILURE = 'EUR/EUR_GET_PERIOD_FAILURE';

