export const USD_GET_REQUEST = 'USD/USD_GET_REQUEST';
export const USD_GET_SUCCESS = 'USD/USD_GET_SUCCESS';
export const USD_GET_FAILURE = 'USD/USD_GET_FAILURE';

export const USD_GET_PERIOD_REQUEST = 'USD/USD_GET_PERIOD_REQUEST';
export const USD_GET_PERIOD_SUCCESS = 'USD/USD_GET_PERIOD_SUCCESS';
export const USD_GET_PERIOD_FAILURE = 'USD/USD_GET_PERIOD_FAILURE';