export const RUR_GET_REQUEST = 'RUR/RUR_GET_REQUEST';
export const RUR_GET_SUCCESS = 'RUR/RUR_GET_SUCCESS';
export const RUR_GET_FAILURE = 'RUR/RUR_GET_FAILURE';

export const RUR_GET_PERIOD_REQUEST = 'RUR/RUR_GET_PERIOD_REQUEST';
export const RUR_GET_PERIOD_SUCCESS = 'RUR/RUR_GET_PERIOD_SUCCESS';
export const RUR_GET_PERIOD_FAILURE = 'RUR/RUR_GET_PERIOD_FAILURE';
